name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  swiftLint:
    name: Lint
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint code using SwiftLint
        run: |
          cd YoutubeClone
          swiftlint lint --reporter github-actions-logging
